export const eduData = [
  {
    title: "Interaksi Manusia Komputer",
    abbr: "IMK",
    day: "Senin",
    time: "10:30 - 13:30",
    lect: ["Alfarissi, M.Comp.Sc."],
    href: "#",
    mkstat: "ongoing",
  },
  {
    title: "Sistem Operasi",
    abbr: "SO",
    day: "Rabu",
    time: "08:00 - 10:30",
    lect: ["Osvari Arsalan, S.Kom., M.T."],
    href: "https://classroom.google.com/c/NDUzNjc2OTI5MTUx?cjc=eaa6icg",
    mkstat: "ongoing",
  },
  {
    title: "Praktikum Sistem Operasi",
    abbr: "SO",
    day: "Jum'at",
    time: "10:00 - 12:00",
    lect: ["Osvari Arsalan, S.Kom., M.T."],
    href: "https://classroom.google.com/c/NDUzNjc2OTI5MjU3?cjc=7krerfm",
    mkstat: "ongoing",
  },
  {
    title: "Grafika Komputer",
    abbr: "Grafkom",
    day: "Kamis",
    time: "08:00 - 10:30",
    lect: [
      "Muhammad Qurhanul Rizqie, S.Kom., M.T., Ph.D.",
      "Samsuryadi, M.Kom., Ph.D.",
    ],
    href: "https://elearning212.unsri.ac.id/course/view.php?id=1144",
    mkstat: "ongoing",
  },
  {
    title: "Teori Bahasa dan Otomata",
    abbr: "TBO",
    day: "Kamis",
    time: "10:30 - 13.30",
    lect: ["Yunita, S.SI., M.CS."],
    href: "https://elearning212.unsri.ac.id/course/view.php?id=1145",
    mkstat: "ongoing",
  },
  {
    title: "Rekayasa Perangkat Lunak",
    abbr: "RPL",
    day: "Kamis",
    time: "13:30 - 16:00",
    lect: ["Annisa Darmawahyuni, M.Kom."],
    href: "https://elearning212.unsri.ac.id/course/view.php?id=633",
    mkstat: "ongoing",
  },
  {
    title: "Jaringan Komputer",
    abbr: "Jarkom",
    day: "Senin",
    time: "08:00 - 10:30",
    lect: ["Hadipurnawan Satria, Ph.D."],
    href: "https://elearning212.unsri.ac.id/course/view.php?id=1146",
    mkstat: "ongoing",
  },
  {
    title: "Praktikum Jaringan Komputer",
    abbr: "Jarkom",
    day: "Senin",
    time: "13:30 - 15:30",
    lect: ["Hadipurnawan Satria, Ph.D."],
    href: "https://elearning212.unsri.ac.id/course/view.php?id=1148",
    mkstat: "ongoing",
  },
  {
    title: "Pemrograman Berorientasi Objek",
    abbr: "PBO",
    day: "Selasa",
    time: "08:00 - 10:30",
    lect: ["Kanda Januar Miraswan, M.T."],
    href: "#",
    mkstat: "ongoing",
  },
  {
    title: "Praktikum Pemrograman Berorientasi Objek",
    abbr: "PBO",
    day: "Selasa",
    time: "13:30 - 15:30",
    lect: ["Kanda Januar Miraswan, M.T."],
    href: "#",
    mkstat: "ongoing",
  },
];
