title: Lapprealm # name of the site
author: Irvan Malik Azantha # name of site's author
email: irvanmalik48@gmail.com # email of site's author
url: https://irvanmalik48.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  Do what you want and do it right.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
